# Generated by cucumber-sinatra. (2015-02-10 14:52:58 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/smarttwit.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SmartTwit

class SmartTwitWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SmartTwitWorld.new
end
